/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as EventsRouteImport } from './routes/events'
import { Route as GivingRouteImport } from './routes/giving'
import { Route as LiveRouteImport } from './routes/live'
import { Route as MinistriesRouteImport } from './routes/ministries'
import { Route as PrayerRouteImport } from './routes/prayer'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SermonsRouteImport } from './routes/sermons'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const GivingRoute = GivingRouteImport.update({
  id: '/giving',
  path: '/giving',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const MinistriesRoute = MinistriesRouteImport.update({
  id: '/ministries',
  path: '/ministries',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerRoute = PrayerRouteImport.update({
  id: '/prayer',
  path: '/prayer',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SermonsRoute = SermonsRouteImport.update({
  id: '/sermons',
  path: '/sermons',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/delete-account': typeof DeleteAccountRoute
  '/events': typeof EventsRoute
  '/giving': typeof GivingRoute
  '/live': typeof LiveRoute
  '/ministries': typeof MinistriesRoute
  '/prayer': typeof PrayerRoute
  '/privacy': typeof PrivacyRoute
  '/sermons': typeof SermonsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/delete-account': typeof DeleteAccountRoute
  '/events': typeof EventsRoute
  '/giving': typeof GivingRoute
  '/live': typeof LiveRoute
  '/ministries': typeof MinistriesRoute
  '/prayer': typeof PrayerRoute
  '/privacy': typeof PrivacyRoute
  '/sermons': typeof SermonsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/delete-account': typeof DeleteAccountRoute
  '/events': typeof EventsRoute
  '/giving': typeof GivingRoute
  '/live': typeof LiveRoute
  '/ministries': typeof MinistriesRoute
  '/prayer': typeof PrayerRoute
  '/privacy': typeof PrivacyRoute
  '/sermons': typeof SermonsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/delete-account'
    | '/events'
    | '/giving'
    | '/live'
    | '/ministries'
    | '/prayer'
    | '/privacy'
    | '/sermons'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/delete-account'
    | '/events'
    | '/giving'
    | '/live'
    | '/ministries'
    | '/prayer'
    | '/privacy'
    | '/sermons'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/delete-account'
    | '/events'
    | '/giving'
    | '/live'
    | '/ministries'
    | '/prayer'
    | '/privacy'
    | '/sermons'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  DeleteAccountRoute: typeof DeleteAccountRoute
  EventsRoute: typeof EventsRoute
  GivingRoute: typeof GivingRoute
  LiveRoute: typeof LiveRoute
  MinistriesRoute: typeof MinistriesRoute
  PrayerRoute: typeof PrayerRoute
  PrivacyRoute: typeof PrivacyRoute
  SermonsRoute: typeof SermonsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giving': {
      id: '/giving'
      path: '/giving'
      fullPath: '/giving'
      preLoaderRoute: typeof GivingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ministries': {
      id: '/ministries'
      path: '/ministries'
      fullPath: '/ministries'
      preLoaderRoute: typeof MinistriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer': {
      id: '/prayer'
      path: '/prayer'
      fullPath: '/prayer'
      preLoaderRoute: typeof PrayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sermons': {
      id: '/sermons'
      path: '/sermons'
      fullPath: '/sermons'
      preLoaderRoute: typeof SermonsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  DeleteAccountRoute: DeleteAccountRoute,
  EventsRoute: EventsRoute,
  GivingRoute: GivingRoute,
  LiveRoute: LiveRoute,
  MinistriesRoute: MinistriesRoute,
  PrayerRoute: PrayerRoute,
  PrivacyRoute: PrivacyRoute,
  SermonsRoute: SermonsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
